/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultationsRouteImport } from './routes/consultations'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSecretaryRouteImport } from './routes/dashboard.secretary'
import { Route as DashboardPatientRouteImport } from './routes/dashboard.patient'
import { Route as DashboardDoctorRouteImport } from './routes/dashboard.doctor'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin.forgot-password'
import { Route as AdminAppRouteImport } from './routes/admin._app'
import { Route as AdminAppIndexRouteImport } from './routes/admin._app.index'
import { Route as AdminAppTestimonialsRouteImport } from './routes/admin._app.testimonials'
import { Route as AdminAppSocialRouteImport } from './routes/admin._app.social'
import { Route as AdminAppSettingsRouteImport } from './routes/admin._app.settings'
import { Route as AdminAppProfileRouteImport } from './routes/admin._app.profile'
import { Route as AdminAppOffersRouteImport } from './routes/admin._app.offers'
import { Route as AdminAppMediaRouteImport } from './routes/admin._app.media'
import { Route as AdminAppHeroRouteImport } from './routes/admin._app.hero'
import { Route as AdminAppGalleryRouteImport } from './routes/admin._app.gallery'
import { Route as AdminAppFaqRouteImport } from './routes/admin._app.faq'
import { Route as AdminAppDoctorRouteImport } from './routes/admin._app.doctor'
import { Route as AdminAppContactRouteImport } from './routes/admin._app.contact'
import { Route as AdminAppBeforeAfterRouteImport } from './routes/admin._app.before-after'
import { Route as AdminAppAboutRouteImport } from './routes/admin._app.about'
import { Route as AdminAppServicesIndexRouteImport } from './routes/admin._app.services.index'
import { Route as AdminAppServicesNewRouteImport } from './routes/admin._app.services.new'
import { Route as AdminAppServicesIdEditRouteImport } from './routes/admin._app.services.$id.edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationsRoute = ConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSecretaryRoute = DashboardSecretaryRouteImport.update({
  id: '/dashboard/secretary',
  path: '/dashboard/secretary',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPatientRoute = DashboardPatientRouteImport.update({
  id: '/dashboard/patient',
  path: '/dashboard/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDoctorRoute = DashboardDoctorRouteImport.update({
  id: '/dashboard/doctor',
  path: '/dashboard/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppRoute = AdminAppRouteImport.update({
  id: '/admin/_app',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppIndexRoute = AdminAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppTestimonialsRoute = AdminAppTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppSocialRoute = AdminAppSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppSettingsRoute = AdminAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppProfileRoute = AdminAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppOffersRoute = AdminAppOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppMediaRoute = AdminAppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppHeroRoute = AdminAppHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppGalleryRoute = AdminAppGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppFaqRoute = AdminAppFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppDoctorRoute = AdminAppDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppContactRoute = AdminAppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppBeforeAfterRoute = AdminAppBeforeAfterRouteImport.update({
  id: '/before-after',
  path: '/before-after',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppAboutRoute = AdminAppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppServicesIndexRoute = AdminAppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppServicesNewRoute = AdminAppServicesNewRouteImport.update({
  id: '/services/new',
  path: '/services/new',
  getParentRoute: () => AdminAppRoute,
} as any)
const AdminAppServicesIdEditRoute = AdminAppServicesIdEditRouteImport.update({
  id: '/services/$id/edit',
  path: '/services/$id/edit',
  getParentRoute: () => AdminAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/booking': typeof BookingRoute
  '/consultations': typeof ConsultationsRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AdminAppRouteWithChildren
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/doctor': typeof DashboardDoctorRoute
  '/dashboard/patient': typeof DashboardPatientRoute
  '/dashboard/secretary': typeof DashboardSecretaryRoute
  '/admin/about': typeof AdminAppAboutRoute
  '/admin/before-after': typeof AdminAppBeforeAfterRoute
  '/admin/contact': typeof AdminAppContactRoute
  '/admin/doctor': typeof AdminAppDoctorRoute
  '/admin/faq': typeof AdminAppFaqRoute
  '/admin/gallery': typeof AdminAppGalleryRoute
  '/admin/hero': typeof AdminAppHeroRoute
  '/admin/media': typeof AdminAppMediaRoute
  '/admin/offers': typeof AdminAppOffersRoute
  '/admin/profile': typeof AdminAppProfileRoute
  '/admin/settings': typeof AdminAppSettingsRoute
  '/admin/social': typeof AdminAppSocialRoute
  '/admin/testimonials': typeof AdminAppTestimonialsRoute
  '/admin/': typeof AdminAppIndexRoute
  '/admin/services/new': typeof AdminAppServicesNewRoute
  '/admin/services/': typeof AdminAppServicesIndexRoute
  '/admin/services/$id/edit': typeof AdminAppServicesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/booking': typeof BookingRoute
  '/consultations': typeof ConsultationsRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/doctor': typeof DashboardDoctorRoute
  '/dashboard/patient': typeof DashboardPatientRoute
  '/dashboard/secretary': typeof DashboardSecretaryRoute
  '/admin/about': typeof AdminAppAboutRoute
  '/admin/before-after': typeof AdminAppBeforeAfterRoute
  '/admin/contact': typeof AdminAppContactRoute
  '/admin/doctor': typeof AdminAppDoctorRoute
  '/admin/faq': typeof AdminAppFaqRoute
  '/admin/gallery': typeof AdminAppGalleryRoute
  '/admin/hero': typeof AdminAppHeroRoute
  '/admin/media': typeof AdminAppMediaRoute
  '/admin/offers': typeof AdminAppOffersRoute
  '/admin/profile': typeof AdminAppProfileRoute
  '/admin/settings': typeof AdminAppSettingsRoute
  '/admin/social': typeof AdminAppSocialRoute
  '/admin/testimonials': typeof AdminAppTestimonialsRoute
  '/admin': typeof AdminAppIndexRoute
  '/admin/services/new': typeof AdminAppServicesNewRoute
  '/admin/services': typeof AdminAppServicesIndexRoute
  '/admin/services/$id/edit': typeof AdminAppServicesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/booking': typeof BookingRoute
  '/consultations': typeof ConsultationsRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/_app': typeof AdminAppRouteWithChildren
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/doctor': typeof DashboardDoctorRoute
  '/dashboard/patient': typeof DashboardPatientRoute
  '/dashboard/secretary': typeof DashboardSecretaryRoute
  '/admin/_app/about': typeof AdminAppAboutRoute
  '/admin/_app/before-after': typeof AdminAppBeforeAfterRoute
  '/admin/_app/contact': typeof AdminAppContactRoute
  '/admin/_app/doctor': typeof AdminAppDoctorRoute
  '/admin/_app/faq': typeof AdminAppFaqRoute
  '/admin/_app/gallery': typeof AdminAppGalleryRoute
  '/admin/_app/hero': typeof AdminAppHeroRoute
  '/admin/_app/media': typeof AdminAppMediaRoute
  '/admin/_app/offers': typeof AdminAppOffersRoute
  '/admin/_app/profile': typeof AdminAppProfileRoute
  '/admin/_app/settings': typeof AdminAppSettingsRoute
  '/admin/_app/social': typeof AdminAppSocialRoute
  '/admin/_app/testimonials': typeof AdminAppTestimonialsRoute
  '/admin/_app/': typeof AdminAppIndexRoute
  '/admin/_app/services/new': typeof AdminAppServicesNewRoute
  '/admin/_app/services/': typeof AdminAppServicesIndexRoute
  '/admin/_app/services/$id/edit': typeof AdminAppServicesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/booking'
    | '/consultations'
    | '/contact'
    | '/doctors'
    | '/faq'
    | '/gallery'
    | '/pricing'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/blog/$slug'
    | '/dashboard/doctor'
    | '/dashboard/patient'
    | '/dashboard/secretary'
    | '/admin/about'
    | '/admin/before-after'
    | '/admin/contact'
    | '/admin/doctor'
    | '/admin/faq'
    | '/admin/gallery'
    | '/admin/hero'
    | '/admin/media'
    | '/admin/offers'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/social'
    | '/admin/testimonials'
    | '/admin/'
    | '/admin/services/new'
    | '/admin/services/'
    | '/admin/services/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/booking'
    | '/consultations'
    | '/contact'
    | '/doctors'
    | '/faq'
    | '/gallery'
    | '/pricing'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/blog/$slug'
    | '/dashboard/doctor'
    | '/dashboard/patient'
    | '/dashboard/secretary'
    | '/admin/about'
    | '/admin/before-after'
    | '/admin/contact'
    | '/admin/doctor'
    | '/admin/faq'
    | '/admin/gallery'
    | '/admin/hero'
    | '/admin/media'
    | '/admin/offers'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/social'
    | '/admin/testimonials'
    | '/admin'
    | '/admin/services/new'
    | '/admin/services'
    | '/admin/services/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/booking'
    | '/consultations'
    | '/contact'
    | '/doctors'
    | '/faq'
    | '/gallery'
    | '/pricing'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/_app'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/blog/$slug'
    | '/dashboard/doctor'
    | '/dashboard/patient'
    | '/dashboard/secretary'
    | '/admin/_app/about'
    | '/admin/_app/before-after'
    | '/admin/_app/contact'
    | '/admin/_app/doctor'
    | '/admin/_app/faq'
    | '/admin/_app/gallery'
    | '/admin/_app/hero'
    | '/admin/_app/media'
    | '/admin/_app/offers'
    | '/admin/_app/profile'
    | '/admin/_app/settings'
    | '/admin/_app/social'
    | '/admin/_app/testimonials'
    | '/admin/_app/'
    | '/admin/_app/services/new'
    | '/admin/_app/services/'
    | '/admin/_app/services/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  BookingRoute: typeof BookingRoute
  ConsultationsRoute: typeof ConsultationsRoute
  ContactRoute: typeof ContactRoute
  DoctorsRoute: typeof DoctorsRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AdminAppRoute: typeof AdminAppRouteWithChildren
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  DashboardDoctorRoute: typeof DashboardDoctorRoute
  DashboardPatientRoute: typeof DashboardPatientRoute
  DashboardSecretaryRoute: typeof DashboardSecretaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultations': {
      id: '/consultations'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof ConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/secretary': {
      id: '/dashboard/secretary'
      path: '/dashboard/secretary'
      fullPath: '/dashboard/secretary'
      preLoaderRoute: typeof DashboardSecretaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/patient': {
      id: '/dashboard/patient'
      path: '/dashboard/patient'
      fullPath: '/dashboard/patient'
      preLoaderRoute: typeof DashboardPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/doctor': {
      id: '/dashboard/doctor'
      path: '/dashboard/doctor'
      fullPath: '/dashboard/doctor'
      preLoaderRoute: typeof DashboardDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_app': {
      id: '/admin/_app'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_app/': {
      id: '/admin/_app/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAppIndexRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/testimonials': {
      id: '/admin/_app/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminAppTestimonialsRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/social': {
      id: '/admin/_app/social'
      path: '/social'
      fullPath: '/admin/social'
      preLoaderRoute: typeof AdminAppSocialRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/settings': {
      id: '/admin/_app/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAppSettingsRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/profile': {
      id: '/admin/_app/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminAppProfileRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/offers': {
      id: '/admin/_app/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminAppOffersRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/media': {
      id: '/admin/_app/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminAppMediaRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/hero': {
      id: '/admin/_app/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminAppHeroRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/gallery': {
      id: '/admin/_app/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminAppGalleryRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/faq': {
      id: '/admin/_app/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminAppFaqRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/doctor': {
      id: '/admin/_app/doctor'
      path: '/doctor'
      fullPath: '/admin/doctor'
      preLoaderRoute: typeof AdminAppDoctorRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/contact': {
      id: '/admin/_app/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminAppContactRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/before-after': {
      id: '/admin/_app/before-after'
      path: '/before-after'
      fullPath: '/admin/before-after'
      preLoaderRoute: typeof AdminAppBeforeAfterRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/about': {
      id: '/admin/_app/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAppAboutRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/services/': {
      id: '/admin/_app/services/'
      path: '/services'
      fullPath: '/admin/services/'
      preLoaderRoute: typeof AdminAppServicesIndexRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/services/new': {
      id: '/admin/_app/services/new'
      path: '/services/new'
      fullPath: '/admin/services/new'
      preLoaderRoute: typeof AdminAppServicesNewRouteImport
      parentRoute: typeof AdminAppRoute
    }
    '/admin/_app/services/$id/edit': {
      id: '/admin/_app/services/$id/edit'
      path: '/services/$id/edit'
      fullPath: '/admin/services/$id/edit'
      preLoaderRoute: typeof AdminAppServicesIdEditRouteImport
      parentRoute: typeof AdminAppRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface AdminAppRouteChildren {
  AdminAppAboutRoute: typeof AdminAppAboutRoute
  AdminAppBeforeAfterRoute: typeof AdminAppBeforeAfterRoute
  AdminAppContactRoute: typeof AdminAppContactRoute
  AdminAppDoctorRoute: typeof AdminAppDoctorRoute
  AdminAppFaqRoute: typeof AdminAppFaqRoute
  AdminAppGalleryRoute: typeof AdminAppGalleryRoute
  AdminAppHeroRoute: typeof AdminAppHeroRoute
  AdminAppMediaRoute: typeof AdminAppMediaRoute
  AdminAppOffersRoute: typeof AdminAppOffersRoute
  AdminAppProfileRoute: typeof AdminAppProfileRoute
  AdminAppSettingsRoute: typeof AdminAppSettingsRoute
  AdminAppSocialRoute: typeof AdminAppSocialRoute
  AdminAppTestimonialsRoute: typeof AdminAppTestimonialsRoute
  AdminAppIndexRoute: typeof AdminAppIndexRoute
  AdminAppServicesNewRoute: typeof AdminAppServicesNewRoute
  AdminAppServicesIndexRoute: typeof AdminAppServicesIndexRoute
  AdminAppServicesIdEditRoute: typeof AdminAppServicesIdEditRoute
}

const AdminAppRouteChildren: AdminAppRouteChildren = {
  AdminAppAboutRoute: AdminAppAboutRoute,
  AdminAppBeforeAfterRoute: AdminAppBeforeAfterRoute,
  AdminAppContactRoute: AdminAppContactRoute,
  AdminAppDoctorRoute: AdminAppDoctorRoute,
  AdminAppFaqRoute: AdminAppFaqRoute,
  AdminAppGalleryRoute: AdminAppGalleryRoute,
  AdminAppHeroRoute: AdminAppHeroRoute,
  AdminAppMediaRoute: AdminAppMediaRoute,
  AdminAppOffersRoute: AdminAppOffersRoute,
  AdminAppProfileRoute: AdminAppProfileRoute,
  AdminAppSettingsRoute: AdminAppSettingsRoute,
  AdminAppSocialRoute: AdminAppSocialRoute,
  AdminAppTestimonialsRoute: AdminAppTestimonialsRoute,
  AdminAppIndexRoute: AdminAppIndexRoute,
  AdminAppServicesNewRoute: AdminAppServicesNewRoute,
  AdminAppServicesIndexRoute: AdminAppServicesIndexRoute,
  AdminAppServicesIdEditRoute: AdminAppServicesIdEditRoute,
}

const AdminAppRouteWithChildren = AdminAppRoute._addFileChildren(
  AdminAppRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  BookingRoute: BookingRoute,
  ConsultationsRoute: ConsultationsRoute,
  ContactRoute: ContactRoute,
  DoctorsRoute: DoctorsRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AdminAppRoute: AdminAppRouteWithChildren,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  DashboardDoctorRoute: DashboardDoctorRoute,
  DashboardPatientRoute: DashboardPatientRoute,
  DashboardSecretaryRoute: DashboardSecretaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
